actions:

  IDLE:
    - ['delay', 0.1 ]

  LIGHT_ATTACK: &LIGHT_ATTACK
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
  
  HEAVY_ATTACK:
    - ['press_mouse', 'right']
    - ['delay', 0.15]
    - ['release_mouse', 'right']
    - ['delay', 2.53]
  
  DRINK_POTION:
    - ['press', 'space']
    - ['delay', 0.16]
    - ['release', 'space']
    - ['delay', 0.34]
    - ['press', 'r']
    - ['delay', 0.12]
    - ['release', 'r']
    - ['delay', 1]
  
  DODGE: &DODGE
    - ['press', 'space']
    - ['delay', 0.16]
    - ['release', 'space']
    - ['delay', 0.34]

  DODGE_TWO: &DODGE_TWO
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.2 ]
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.34 ]

  DODGE_THREE:
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.2 ]
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.2 ]
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.34 ]

  ATTACK_DODGE:
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
    - ['press', 'space']
    - ['delay', 0.16]
    - ['release', 'space']
    - ['delay', 0.34]  
  
  QIESHOU:
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
    - ['press_mouse', 'right']
    - ['delay', 0.15]
    - ['release_mouse', 'right']
    - ['delay', 0.96]

  THREE_HIT_COMBO: &THREE_HIT_COMBO
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.13 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.3 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.14 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.32 ]
    - *DODGE

  FIVE_HIT_COMBO:
    - ['press_mouse', 'left']
    - ['delay', 0.13 ]
    - ['release_mouse', 'left']
    - ['delay', 0.3]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.62]
    - ['press_mouse', 'left']
    - ['delay', 0.17 ]
    - ['release_mouse', 'left']
    - ['delay', 0.73]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 1]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 1]

  SKILL_1: &SKILL_1
    - ['press', '1']
    - ['delay', 0.16]
    - ['release', '1']
    - ['delay', 0.4]
  
  SKILL_2: &SKILL_2
    - ['press', '2']
    - ['delay', 0.16]
    - ['release', '2']
    - ['delay', 0.4]
  
  SKILL_3: &SKILL_3
    - ['press', '3']
    - ['delay', 0.16]
    - ['release', '3']
    - ['delay', 1.90]
  
  SKILL_4: &SKILL_4
    - ['press', '4']
    - ['delay', 0.16]
    - ['release', '4']
    - ['delay', 1.19]

  RUN_CHARGE:  &RUN_CHARGE
    - [ 'delay', 0.16 ]
    - [ 'press_mouse', 'right' ]
    - [ 'press', 'shift' ]
    - [ 'delay', 0.2 ]
    - [ 'press', 'd' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'd' ]
    - [ 'press', 'w' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'w' ]
    - [ 'press', 'a' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'a' ]
    - [ 'press', 'w' ]
    - [ 'delay', 1 ]
    - [ 'release', 'w' ]
    - [ 'delay', 0.2 ]
    - [ 'release', 'shift' ]
    - [ 'release_mouse', 'right' ]
    - [ 'delay', 3.4 ]

  STEALTH_CHARGE:
    - *SKILL_2
    - *RUN_CHARGE


  DING_CHARGE:
    - *SKILL_1
    - [ 'delay', 0.16 ]
    - [ 'press_mouse', 'right' ]
    - [ 'press', 'shift' ]
    - [ 'delay', 0.2 ]
    - [ 'press', 'd' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'd' ]
    - [ 'press', 'w' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'w' ]
    - [ 'press', 'a' ]
    - [ 'delay', 1.45 ]
    - [ 'release', 'a' ]
    - [ 'press', 'w' ]
    - [ 'delay', 1 ]
    - [ 'release', 'w' ]
    - [ 'delay', 0.2 ]
    - [ 'release', 'shift' ]
    - [ 'release_mouse', 'right' ]
    - [ 'delay', 3.4 ]

  STEALTH_DRINK:
    - *SKILL_2
    - [ 'delay', 0.6 ]
    - [ 'press', 'r' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'r' ]
    - [ 'delay', 0.8 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.13 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 1.7 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.13 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.15 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.14 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.15 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.14 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.15 ]
    - [ 'press_mouse', 'left' ]
    - [ 'delay', 0.14 ]
    - [ 'release_mouse', 'left' ]
    - [ 'delay', 0.25 ]
    - [ 'press', 'space' ]
    - [ 'delay', 0.16 ]
    - [ 'release', 'space' ]
    - [ 'delay', 0.34 ]

  FABAO:
    - ['press', 't']
    - ['delay', 0.16]
    - ['release', 't']
    - ['delay', 1.55]
  
  TISHEN:
    - ['press', 'f']
    - ['delay', 0.16]
    - ['release', 'f']
    - ['delay', 4.15]

  MOVE_CAMERA_RIGHT:
    - ['move_mouse', 300, 0, 1]
    - ['delay', 1]

  MOVE_CAMERA_LEFT:
    - ['move_mouse', -300, 0, 1]
    - ['delay', 1]

  RUN_FORWARD: &RUN_FORWARD
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'w']
    - ['delay', 1]
    - ['release', 'w']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_BACKWARD: &RUN_BACKWARD
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 's']
    - ['delay', 1]
    - ['release', 's']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_LEFT: &RUN_LEFT
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'a']
    - ['delay', 1]
    - ['release', 'a']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_RIGHT: &RUN_RIGHT
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'd']
    - ['delay', 1]
    - ['release', 'd']
    - ['delay', 0.2]
    - ['release', 'shift']

  SKIP_CG:
    - ['delay', 1]
    - ['press', 'e']
    - ['delay', 3]
    - ['release', 'e']
    - ['delay', 4]

  YINHU_RESTART:
    - ['delay', 0.2]
    - *RUN_FORWARD
    - ['delay', 1]
    - ['press', 'e']
    - ['delay', 0.5]
    - ['release', 'e']
    - ['delay', 6]
    - ['press', 'down']
    - ['delay', 0.2]
    - ['release', 'down']
    - ['delay', 0.2]
    - ['press', 'down']
    - ['delay', 0.2]
    - ['release', 'down']
    - ['delay', 1]
    - ['press', 'e']
    - ['delay', 0.5]
    - ['release', 'e']
    - ['delay', 2]
    - ['press', 'e']
    - ['delay', 3]
    - ['release', 'e']
    - ['delay', 6]
    - *RUN_FORWARD

  huxianfeng_restart_v2:
    - *RUN_FORWARD
    - [ 'press', 'w' ]
    - [ 'delay', 7 ]
    - ['release', 'w']
    - *RUN_FORWARD
    - [ 'press_mouse', 'middle' ]
    - [ 'release_mouse', 'middle' ]

no_interrupts:
  - STEALTH_CHARGE
  - STEALTH_DRINK
  - LIGHT_ATTACK
  - DODGE
  - IDLE

hot_list:
  - IDLE
  - LIGHT_ATTACK
  - HEAVY_ATTACK
  - DRINK_POTION
  - DODGE
  - DODGE_TWO
  - DODGE_THREE
  - ATTACK_DODGE
  - QIESHOU
  - FIVE_HIT_COMBO
  - SKILL_1
  - STEALTH_CHARGE
  - SKILL_3
  - FABAO
  - TISHEN
  - STEALTH_DRINK


